rm chrome/app/theme/default_100_percent/ash/newtab_button_mask.png
rm chrome/app/theme/default_100_percent/ash/newtab_hover.png
rm chrome/app/theme/default_100_percent/ash/newtab_normal.png
rm chrome/app/theme/default_100_percent/ash/newtab_pressed.png
rm chrome/app/theme/default_100_percent/omnibox_history.png
rm chrome/app/theme/default_100_percent/omnibox_history_dark.png
rm chrome/app/theme/default_100_percent/omnibox_history_selected.png
rm chrome/app/theme/default_200_percent/content_top_center.png
rm chrome/app/theme/default_200_percent/content_top_left_corner.png
rm chrome/app/theme/default_200_percent/content_top_left_corner_mask.png
rm chrome/app/theme/default_200_percent/content_top_right_corner.png
rm chrome/app/theme/default_200_percent/content_top_right_corner_mask.png
rm chrome/app/theme/default_200_percent/stop_disabled.png
rm chrome/app/theme/default_200_percent/tab_active_center.png
rm chrome/app/theme/default_200_percent/tab_active_left.png
rm chrome/app/theme/default_200_percent/tab_active_right.png
rm chrome/app/theme/default_200_percent/tab_alpha_left.png
rm chrome/app/theme/default_200_percent/tab_alpha_right.png
rm chrome/app/theme/default_200_percent/tab_close.png
rm chrome/app/theme/default_200_percent/tab_close_hover.png
rm chrome/app/theme/default_200_percent/tab_close_mask.png
rm chrome/app/theme/default_200_percent/tab_close_pressed.png
rm chrome/app/theme/default_200_percent/tab_inactive_center.png
rm chrome/app/theme/default_200_percent/tab_inactive_left.png
rm chrome/app/theme/default_200_percent/tab_inactive_right.png
rm chrome/app/theme/touch_100_percent/browser_action_hover.png
rm chrome/app/theme/touch_100_percent/browser_action_normal.png
rm chrome/app/theme/touch_100_percent/browser_action_pressed.png
rm chrome/app/theme/touch_100_percent/browser_actions_overflow_hover.png
rm chrome/app/theme/touch_100_percent/browser_actions_overflow_normal.png
rm chrome/app/theme/touch_100_percent/browser_actions_overflow_pressed.png
rm chrome/app/theme/touch_100_percent/browser_back_disabled.png
rm chrome/app/theme/touch_100_percent/browser_back_hover.png
rm chrome/app/theme/touch_100_percent/browser_back_normal.png
rm chrome/app/theme/touch_100_percent/browser_back_pressed.png
rm chrome/app/theme/touch_100_percent/browser_forward_disabled.png
rm chrome/app/theme/touch_100_percent/browser_forward_hover.png
rm chrome/app/theme/touch_100_percent/browser_forward_normal.png
rm chrome/app/theme/touch_100_percent/browser_forward_pressed.png
rm chrome/app/theme/touch_100_percent/browser_home_hover.png
rm chrome/app/theme/touch_100_percent/browser_home_normal.png
rm chrome/app/theme/touch_100_percent/browser_home_pressed.png
rm chrome/app/theme/touch_100_percent/browser_omnibox_border.png
rm chrome/app/theme/touch_100_percent/browser_omnibox_left.png
rm chrome/app/theme/touch_100_percent/browser_omnibox_middle.png
rm chrome/app/theme/touch_100_percent/browser_omnibox_right.png
rm chrome/app/theme/touch_100_percent/browser_reload_hover.png
rm chrome/app/theme/touch_100_percent/browser_reload_normal.png
rm chrome/app/theme/touch_100_percent/browser_reload_pressed.png
rm chrome/app/theme/touch_100_percent/browser_stop_disabled.png
rm chrome/app/theme/touch_100_percent/browser_stop_hover.png
rm chrome/app/theme/touch_100_percent/browser_stop_normal.png
rm chrome/app/theme/touch_100_percent/browser_stop_pressed.png
rm chrome/app/theme/touch_100_percent/browser_tools_hover.png
rm chrome/app/theme/touch_100_percent/browser_tools_normal.png
rm chrome/app/theme/touch_100_percent/browser_tools_pressed.png
rm chrome/app/theme/touch_100_percent/content_top_center.png
rm chrome/app/theme/touch_100_percent/tab_active_center.png
rm chrome/app/theme/touch_100_percent/tab_active_left.png
rm chrome/app/theme/touch_100_percent/tab_active_right.png
rm chrome/app/theme/touch_100_percent/tab_alpha_left.png
rm chrome/app/theme/touch_100_percent/tab_alpha_right.png
rm chrome/app/theme/touch_100_percent/tab_close_hover.png
rm chrome/app/theme/touch_100_percent/tab_close_mask.png
rm chrome/app/theme/touch_100_percent/tab_close_normal.png
rm chrome/app/theme/touch_100_percent/tab_close_pressed.png
rm chrome/app/theme/touch_100_percent/tab_inactive_center.png
rm chrome/app/theme/touch_100_percent/tab_inactive_left.png
rm chrome/app/theme/touch_100_percent/tab_inactive_right.png
rm chrome/app/theme/touch_200_percent/browser_action_hover.png
rm chrome/app/theme/touch_200_percent/browser_action_normal.png
rm chrome/app/theme/touch_200_percent/browser_action_pressed.png
rm chrome/app/theme/touch_200_percent/browser_actions_overflow_hover.png
rm chrome/app/theme/touch_200_percent/browser_actions_overflow_normal.png
rm chrome/app/theme/touch_200_percent/browser_actions_overflow_pressed.png
rm chrome/app/theme/touch_200_percent/browser_back_disabled.png
rm chrome/app/theme/touch_200_percent/browser_back_hover.png
rm chrome/app/theme/touch_200_percent/browser_back_normal.png
rm chrome/app/theme/touch_200_percent/browser_back_pressed.png
rm chrome/app/theme/touch_200_percent/browser_forward_disabled.png
rm chrome/app/theme/touch_200_percent/browser_forward_hover.png
rm chrome/app/theme/touch_200_percent/browser_forward_normal.png
rm chrome/app/theme/touch_200_percent/browser_forward_pressed.png
rm chrome/app/theme/touch_200_percent/browser_home_hover.png
rm chrome/app/theme/touch_200_percent/browser_home_normal.png
rm chrome/app/theme/touch_200_percent/browser_home_pressed.png
rm chrome/app/theme/touch_200_percent/browser_omnibox_left.png
rm chrome/app/theme/touch_200_percent/browser_omnibox_middle.png
rm chrome/app/theme/touch_200_percent/browser_omnibox_right.png
rm chrome/app/theme/touch_200_percent/browser_reload_hover.png
rm chrome/app/theme/touch_200_percent/browser_reload_normal.png
rm chrome/app/theme/touch_200_percent/browser_reload_pressed.png
rm chrome/app/theme/touch_200_percent/browser_stop_disabled.png
rm chrome/app/theme/touch_200_percent/browser_stop_hover.png
rm chrome/app/theme/touch_200_percent/browser_stop_normal.png
rm chrome/app/theme/touch_200_percent/browser_stop_pressed.png
rm chrome/app/theme/touch_200_percent/browser_tools_hover.png
rm chrome/app/theme/touch_200_percent/browser_tools_normal.png
rm chrome/app/theme/touch_200_percent/browser_tools_pressed.png
rm chrome/app/theme/touch_200_percent/newtab_button_mask.png
rm chrome/app/theme/touch_200_percent/newtab_hover.png
rm chrome/app/theme/touch_200_percent/newtab_normal.png
rm chrome/app/theme/touch_200_percent/newtab_pressed.png
rm chrome/app/theme/touch_200_percent/otr_icon.png
rm chrome/app/theme/touch_200_percent/tab_active_center.png
rm chrome/app/theme/touch_200_percent/tab_active_left.png
rm chrome/app/theme/touch_200_percent/tab_active_right.png
rm chrome/app/theme/touch_200_percent/tab_alpha_left.png
rm chrome/app/theme/touch_200_percent/tab_alpha_right.png
rm chrome/app/theme/touch_200_percent/tab_close_hover.png
rm chrome/app/theme/touch_200_percent/tab_close_mask.png
rm chrome/app/theme/touch_200_percent/tab_close_normal.png
rm chrome/app/theme/touch_200_percent/tab_close_pressed.png
rm chrome/app/theme/touch_200_percent/tab_inactive_center.png
rm chrome/app/theme/touch_200_percent/tab_inactive_left.png
rm chrome/app/theme/touch_200_percent/tab_inactive_right.png
rm chrome/browser/resources/print_preview/images/classic_printer_32.png
rm chrome/browser/resources/print_preview/images/cloud_printer_32.png
rm chrome/browser/resources/print_preview/images/cloud_printer_shared_32.png
rm chrome/browser/resources/print_preview/images/mobile_shared_32.png
rm content/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events/scale-and-scroll-iframe-body-expected.png
rm content/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events/scale-and-scroll-iframe-window-expected.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarBlue.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarDarkGreen.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarGray.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarGreen.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarLightPurple.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarOrange.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarPurple.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarRed.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineBarYellow.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineCheckmarks.png
rm third_party/WebKit/Source/WebCore/inspector/front-end/Images/timelineDots.png
rm ui/resources/close_bar.png
rm ui/resources/close_bar_h.png
rm ui/resources/close_bar_mask.png
rm ui/resources/close_bar_p.png
rm ui/resources/default_200_percent/ash/status_accessibility_mode.png
rm ui/resources/default_200_percent/ash/status_volume_all.png
rm ui/resources/default_200_percent/bubble_shadow_b.png
rm ui/resources/default_200_percent/bubble_shadow_bl.png
rm ui/resources/default_200_percent/bubble_shadow_br.png
rm ui/resources/default_200_percent/bubble_shadow_l.png
rm ui/resources/default_200_percent/bubble_shadow_r.png
rm ui/resources/default_200_percent/bubble_shadow_t.png
rm ui/resources/default_200_percent/bubble_shadow_tl.png
rm ui/resources/default_200_percent/bubble_shadow_tr.png
rm ui/resources/folder_closed.png
rm ui/resources/folder_closed_rtl.png
rm ui/resources/folder_open.png
rm ui/resources/folder_open_rtl.png
rm ui/resources/oak.png
rm ui/resources/touch_100_percent/window_button_separator.png
rm ui/resources/touch_100_percent/window_close_hover.png
rm ui/resources/touch_100_percent/window_close_normal.png
rm ui/resources/touch_100_percent/window_close_pressed.png
rm ui/resources/touch_100_percent/window_maximize_hover.png
rm ui/resources/touch_100_percent/window_maximize_normal.png
rm ui/resources/touch_100_percent/window_maximize_pressed.png
rm ui/resources/touch_100_percent/window_maximized_minimize_hover.png
rm ui/resources/touch_100_percent/window_maximized_minimize_normal.png
rm ui/resources/touch_100_percent/window_maximized_minimize_pressed.png
rm ui/resources/touch_100_percent/window_restore_hover.png
rm ui/resources/touch_100_percent/window_restore_normal.png
rm ui/resources/touch_100_percent/window_restore_pressed.png
rm ui/resources/touch_100_percent/window_snap_left_pressed.png
rm ui/resources/touch_100_percent/window_snap_minimize_pressed.png
rm ui/resources/touch_100_percent/window_snap_pressed.png
rm ui/resources/touch_100_percent/window_snap_right_pressed.png
rm ui/resources/touch_200_percent/window_close_hover.png
rm ui/resources/touch_200_percent/window_close_normal.png
rm ui/resources/touch_200_percent/window_close_pressed.png
rm webkit/glue/resources/mediaplayer_sound_disabled_down.png
rm webkit/glue/resources/mediaplayer_sound_disabled_hover.png
